version: '3.8'

x-base:
  &base
  restart: always


services:
  client:
    <<: *base
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - react-express
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - react-express
      - express-mongo


  mongo:
    image: mongo:4.2.0
    volumes:
      - ./mongo:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:
