version: '3.8'

x-base:
  &base
  restart: always


services:
  client:
    <<: *base
    build:
      context: client
#      target: dev-envs
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - react-express
    depends_on:
      - server

  server:
    build:
      context: server
    ports:
      - 3000:3000
#      target: dev-envs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 3000
  mongo:
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:
